Upgrade Crawl4AI
This addresses a pip installation failure:

```
328.1 ERROR: Cannot install -r requirements.txt (line 39) and pillow~=11.1.0 because these package versions have conflicting dependencies.
328.1
328.1 The conflict is caused by:
328.1     The user requested pillow~=11.1.0
328.1     crawl4ai 0.6.3 depends on pillow~=10.4
328.1
328.1 Additionally, some packages in these conflicts have no matching distributions available for your environment:
328.1     pillow
328.1
328.1 To fix this you could try to:
328.1 1. loosen the range of package versions you've specified
328.1 2. remove package versions to allow pip to attempt to solve the dependency conflict
328.1
328.4 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:3
--------------------
   2 |     WORKDIR /root
   3 | >>> RUN git clone https://github.com/FoundationAgents/OpenManus.git \
   4 | >>>  && cd OpenManus \
   5 | >>>  && pip install -r requirements.txt \
   6 | >>>  && playwright install
   7 |     CMD [ "python", "run_mcp_server.py", "--transport=http" ]
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c git clone https://github.com/FoundationAgents/OpenManus.git  && cd OpenManus  && pip install -r requirements.txt  && playwright install" did not complete successfully: exit code: 1
```